src/main/java/com/kenfogel/navigation/QuizBean.java
package com.kenfogel.navigation;

import java.io.Serializable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.enterprise.context.RequestScoped;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;

/**
 * This is a CDI managed bean that is both data and action. Using actions is the
 * preferred way to carry out business processes. Notice that the setters and
 * getters are not balanced.
 *
 * @author Ken
 * @version 1.0
 *
 */
@Named
@SessionScoped
public class QuizBean implements Serializable {

    private static final long serialVersionUID = -1581876369093124639L;

    private int currentProblem;
    private int tries;
    private int score;
    private String response = "";
    private String correctAnswer;

    // The problems are hard wired into the ArrayList. 
    // In a real application they would come from a database. 
    private ArrayList<Problem> problems = new ArrayList<>(Arrays.asList(
            new Problem(
                    "What trademarked slogan describes Java development? Write once, ...",
                    "run anywhere"),
            new Problem(
                    "What are the first 4 bytes of every class file (in hexadecimal)?",
                    "CAFEBABE"),
            new Problem(
                    "What does this statement print? System.out.println(1+\"2\");",
                    "12"),
            new Problem(
                    "Which Java keyword is used to define a subclass?",
                    "extends"),
            new Problem(
                    "What was the original name of the Java programming language?",
                    "Oak"),
            new Problem(
                    "Which java.util class describes a point in time?",
                    "Date")));

    public String getQuestion() {
        return problems.get(currentProblem).getQuestion();
    }

    public String getAnswer() {
        return correctAnswer;
    }

    public int getScore() {
        return score;
    }

    public String getResponse() {
        return response;
    }

    public void setResponse(String newValue) {
        response = newValue;
    }

    /**
     * An action that determines if a guess is right or wrong. The outcome is
     * the navigation rule to be followed.
     *
     * @return navigation rule
     */
    public String answerAction() {
        tries++;
        if (problems.get(currentProblem).isCorrect(response)) {
            score++;
            nextProblem();
            if (currentProblem == problems.size()) {
                return "done";
            } else {
                return "success";
            }
        } else if (tries == 1) {
            return "again";
        } else {
            nextProblem();
            if (currentProblem == problems.size()) {
                return "done";
            } else {
                return "failure";
            }
        }
    }

    /**
     * An action that re-initialized the game so you can play again
     *
     * @return the start-over navigation rule
     */
    public String startOverAction() {
        // Nice touch shuffling the problems
        Collections.shuffle(problems);
        currentProblem = 0;
        score = 0;
        tries = 0;
        response = "";
        return "startOver";
    }

    /**
     * Advance to the next problem
     */
    private void nextProblem() {
        correctAnswer = problems.get(currentProblem).getAnswer();
        currentProblem++;
        tries = 0;
        response = "";
    }
}

src/main/webapp/again.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{msgs.title}"</title>
    </h:head>
    <h:body>
        <h:form>
            <p>#{msgs.notCorrect}</p>
            <p>#{quizBean.question}</p>
            <p><h:inputText value="#{quizBean.response}"/></p>
            <p>
                <h:commandButton value="#{msgs.checkAnswer}"
                                 action="#{quizBean.answerAction}"/>
            </p>
        </h:form>
    </h:body>
</html>

src/main/webapp/done.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
            <p>
                #{msgs.thankYou}
                <h:outputFormat value="#{msgs.score}">
                    <f:param value="#{quizBean.score}"/>
                </h:outputFormat>
            </p>
            <p>
                <h:commandButton value="#{msgs.startOver}"
                                 action="#{quizBean.startOverAction}"/>
            </p>
        </h:form>
    </h:body>
</html>

src/main/webapp/failure.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
            <p>
                #{msgs.stillNotCorrect}"
                <h:outputFormat value="#{msgs.correctAnswer}">
                    <f:param value="#{quizBean.answer}"/>
                </h:outputFormat>
            </p>
            <p>#{msgs.nextProblem}</p>
            <p>#{quizBean.question}</p>
            <p><h:inputText value="#{quizBean.response}"/></p>
            <p>
                <h:commandButton value="#{msgs.checkAnswer}"
                                 action="#{quizBean.answerAction}"/>
            </p>
        </h:form>
    </h:body>
</html>

src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
            <p>#{quizBean.question}</p>
            <p><h:inputText value="#{quizBean.response}"/></p>
            <p>
                <h:commandButton value="#{msgs.checkAnswer}"
                                 action="#{quizBean.answerAction}"/>
            </p>
        </h:form>
    </h:body>
</html>

src/main/webapp/success.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
            <p>
                #{msgs.correct}
                <h:outputFormat value="#{msgs.score}">
                    <f:param value="#{quizBean.score}"/>
                </h:outputFormat>
            </p>
            <p>#{msgs.nextProblem}</p>
            <p>#{quizBean.question}</p>
            <p><h:inputText value="#{quizBean.response}"/></p>
            <p>
                <h:commandButton value="#{msgs.checkAnswer}"
                                 action="#{quizBean.answerAction}"/>
            </p>
        </h:form>
    </h:body>
</html>